name: Ejemplo de Matrix

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run script
        run: |
          echo "Node.js VERSION ${{ matrix.node-version }}"
          npm --version
          
