name: Test Composite Action

on: [push]

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: ls
        uses: ls-al

      - name: ls
        uses: ./.github/actions/my-action
        with:
          message: "Ivan"