name: Hola Mundo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo
        run: echo "Hola Mundo"
      - name: touch file
        run: touch file.txt
      - name: Set text
        run: echo "Hola Mundo 2" > file.txt
      - name: Read file
        run: cat file.txt
      - name: Saludo 5
        run: echo "Hola Mundo 5"

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: LS
        run: ls -al
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest
      - name: node version
        run: node --version
      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: node version
        run: php --version


